apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-2
spec:
  replicas: 2 # Adjust as needed
  selector:
    matchLabels:
      app: react-app-2
  template:
    metadata:
      labels:
        app: react-app-2
    spec:
      containers:
        - name: react-app-2
          imagePullPolicy: Never
          image: k8stest2:latest

---
apiVersion: v1
kind: Service
metadata:
  name: react-app-2-service
spec:
  selector:
    app: react-app-2
  ports:
    - protocol: TCP
      port: 81
      targetPort: 3000
  type: LoadBalancer
